[package]
name = "maman"
version = "0.6.0"
authors = ["Laurent Arnoud <laurent@spkdev.net>"]
description = "Rust Web Crawler"
repository = "https://github.com/spk/maman.git"
homepage = "https://github.com/spk/maman"
keywords = ["web", "crawler", "spider"]
license = "MIT"
readme = "README.md"

[dependencies]
hyper = "0.9"
html5ever = "0.5"
tendril = "0.2"
string_cache = "0.2"
serde = "0.8"
serde_json = "0.8"
url = { version = "1.2", features = ["serde"] }
robotparser = "0.6.0"
sidekiq = "0.3.0"
encoding = "0.2"
log = "0.3"
env_logger = "0.3"
